export default {
    REACT_APP_WEATHER_API_KEY: process.env.REACT_APP_WEATHER_API_KEY,
    REACT_APP_ATTRACTIONS_API_KEY: process.env.REACT_APP_ATTRACTIONS_API_KEY,
    REACT_APP_FOOD_API_KEY:process.env.REACT_APP_FOOD_API_KEY,
    REACT_APP_TRIPOSO_API:process.env.REACT_APP_TRIPOSO_API,
    REACT_APP_BACKEND_API_KEY: process.env.REACT_APP_API_KEY,
}